server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Importante para Single Page Applications (SPA) como Angular
    # Redirige cualquier ruta no encontrada al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
